# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Species.create(name: "African glass catfish")
Species.create(name: "African lungfish")
Species.create(name: "Aholehole")
Species.create(name: "Airbreathing catfish")
Species.create(name: "Airsac catfish")
Species.create(name: "Alaska blackfish")
Species.create(name: "Albacore")
Species.create(name: "Alewife")
Species.create(name: "Alfonsino")
Species.create(name: "Algae eater")
Species.create(name: "Alligatorfish")
Species.create(name: "Amago")
Species.create(name: "American sole")
Species.create(name: "Amur pike")
Species.create(name: "Anchovy")
Species.create(name: "Anemonefish")
Species.create(name: "Angelfish")
Species.create(name: "Angler")
Species.create(name: "Angler catfish")
Species.create(name: "Anglerfish")
Species.create(name: "Antarctic cod")
Species.create(name: "Antarctic icefish")
Species.create(name: "Antenna codlet")
Species.create(name: "Arapaima")
Species.create(name: "Archerfish")
Species.create(name: "Arctic char")
Species.create(name: "Armored gurnard")
Species.create(name: "Armored searobin")
Species.create(name: "Armorhead")
Species.create(name: "Armorhead catfish")
Species.create(name: "Armoured catfish")
Species.create(name: "Arowana")
Species.create(name: "Arrowtooth eel")
Species.create(name: "Aruana")
Species.create(name: "Asian carps")
Species.create(name: "Asiatic glassfish")
Species.create(name: "Atka mackerel")
Species.create(name: "Atlantic cod")
Species.create(name: "Atlantic eel")
Species.create(name: "Atlantic herring")
Species.create(name: "Atlantic salmon")
Species.create(name: "Atlantic saury")
Species.create(name: "Atlantic silverside")
Species.create(name: "Atlantic Trout")
Species.create(name: "Australasian salmon")
Species.create(name: "Australian grayling")
Species.create(name: "Australian herring")
Species.create(name: "Australian lungfish")
Species.create(name: "Australian prowfish")
Species.create(name: "Ayu")
Species.create(name: "Alooh")
Species.create(name: "B[edit]")
Species.create(name: "Baikal oilfish")
Species.create(name: "Bala shark")
Species.create(name: "Ballan wrasse")
Species.create(name: "Bamboo shark")
Species.create(name: "Banded killifish")
Species.create(name: "Bandfish")
Species.create(name: "Banjo")
Species.create(name: "Bangus")
Species.create(name: "Banjo catfish")
Species.create(name: "Barb")
Species.create(name: "Barbel")
Species.create(name: "Barbeled dragonfish")
Species.create(name: "Barbeled houndshark")
Species.create(name: "Barblless Catfish")
Species.create(name: "Barfish")
Species.create(name: "Barracuda")
Species.create(name: "Barracudina")
Species.create(name: "Barramundi")
Species.create(name: "Barred danio")
Species.create(name: "Barreleye")
Species.create(name: "Basking shark")
Species.create(name: "Bass")
Species.create(name: "Basslet")
Species.create(name: "Batfish")
Species.create(name: "Bat ray")
Species.create(name: "Beachsalmon")
Species.create(name: "Beaked salmon")
Species.create(name: "Beaked sandfish")
Species.create(name: "Beardfish")
Species.create(name: "Beluga sturgeon")
Species.create(name: "Bengal danio")
Species.create(name: "Bent Tooth")
Species.create(name: "Betta")
Species.create(name: "Bichir")
Species.create(name: "Bigeye")
Species.create(name: "Bigeye squaretail")
Species.create(name: "Bighead carp")
Species.create(name: "Bigmouth buffalo")
Species.create(name: "Bigscale")
Species.create(name: "Bigscale Fish")
Species.create(name: "Bigscale pomfret")
Species.create(name: "Billfish")
Species.create(name: "Bitterling")
Species.create(name: "Black angelfish")
Species.create(name: "Black bass")
Species.create(name: "Black dragonfish")
Species.create(name: "Blackchin")
Species.create(name: "Blackfish")
Species.create(name: "Blacktip reef shark")
Species.create(name: "Black mackerel")
Species.create(name: "Black Pickerel")
Species.create(name: "Black Prickleback")
Species.create(name: "Black scalyfin")
Species.create(name: "Black sea bass")
Species.create(name: "Black scabbardfish")
Species.create(name: "Blacksmelt")
Species.create(name: "Black swallower")
Species.create(name: "Black tetra")
Species.create(name: "Black triggerfish")
Species.create(name: "Bleak")
Species.create(name: "Blenny")
Species.create(name: "Blind goby")
Species.create(name: "Blind shark")
Species.create(name: "Blobfish")
Species.create(name: "Blowfish")
Species.create(name: "Blue catfish")
Species.create(name: "Blue danio")
Species.create(name: "Blue-redstripe danio")
Species.create(name: "Blue eye")
Species.create(name: "Bluefin tuna")
Species.create(name: "Bluefish")
Species.create(name: "Bluegill")
Species.create(name: "Blue gourami")
Species.create(name: "Blue shark")
Species.create(name: "Blue triggerfish")
Species.create(name: "Blue whiting")
Species.create(name: "Bluntnose knifefish")
Species.create(name: "Bluntnose minnow")
Species.create(name: "Boafish")
Species.create(name: "Boarfish")
Species.create(name: "Bobtail snipe eel")
Species.create(name: "Bocaccio")
Species.create(name: "Boga")
Species.create(name: "Bombay duck")
Species.create(name: "Bonefish")
Species.create(name: "Bonito")
Species.create(name: "Bonnetmouth")
Species.create(name: "Bonytail chub")
Species.create(name: "Bonytongue")
Species.create(name: "Bowfin")
Species.create(name: "Boxfish")
Species.create(name: "Bramble shark")
Species.create(name: "Bream")
Species.create(name: "Brill")
Species.create(name: "Bristlemouth")
Species.create(name: "Bristlenose catfish")
Species.create(name: "Broadband dogfish")
Species.create(name: "Brook lamprey")
Species.create(name: "Brook trout")
Species.create(name: "Brotula")
Species.create(name: "Brown trout")
Species.create(name: "Buffalofish")
Species.create(name: "Bullhead")
Species.create(name: "Bullhead shark")
Species.create(name: "Bull shark")
Species.create(name: "Bull trout")
Species.create(name: "Burbot")
Species.create(name: "Buri")
Species.create(name: "Burma danio")
Species.create(name: "Burrowing goby")
Species.create(name: "Butterfly ray")
Species.create(name: "Butterflyfish")
Species.create(name: "C[edit]")
Species.create(name: "California flyingfish")
Species.create(name: "California halibut")
Species.create(name: "California smoothtongue")
Species.create(name: "Canary rockfish")
Species.create(name: "Candiru")
Species.create(name: "Candlefish")
Species.create(name: "Capelin")
Species.create(name: "Cardinalfish")
Species.create(name: "Carp")
Species.create(name: "Carpetshark")
Species.create(name: "Carpsucker")
Species.create(name: "Catalufa")
Species.create(name: "Catfish")
Species.create(name: "Catla")
Species.create(name: "Cat shark")
Species.create(name: "Cavefish")
Species.create(name: "Celebes rainbowfish")
Species.create(name: "Central mudminnow")
Species.create(name: "Cepalin")
Species.create(name: "Chain pickerel")
Species.create(name: "Channel bass")
Species.create(name: "Channel catfish")
Species.create(name: "Char")
Species.create(name: "Cherry salmon")
Species.create(name: "Chimaera")
Species.create(name: "Chinook salmon")
Species.create(name: "Cherubfish")
Species.create(name: "Chub")
Species.create(name: "Chubsucker")
Species.create(name: "Chum salmon")
Species.create(name: "Cichlid")
Species.create(name: "Cisco")
Species.create(name: "Climbing catfish")
Species.create(name: "Climbing gourami")
Species.create(name: "Climbing perch")
Species.create(name: "Clingfish")
Species.create(name: "Clownfish")
Species.create(name: "Clown loach")
Species.create(name: "Clown triggerfish")
Species.create(name: "Cobbler")
Species.create(name: "Cobia")
Species.create(name: "Cod")
Species.create(name: "Cod icefish")
Species.create(name: "Codlet")
Species.create(name: "Codling")
Species.create(name: "Coelacanth")
Species.create(name: "Coffinfish")
Species.create(name: "Coho salmon")
Species.create(name: "Coley")
Species.create(name: "Collared carpetshark")
Species.create(name: "Collared dogfish")
Species.create(name: "Colorado squawfish")
Species.create(name: "Combfish")
Species.create(name: "Combtail gourami")
Species.create(name: "Combtooth blenny")
Species.create(name: "Common carp")
Species.create(name: "Common tunny")
Species.create(name: "Conger eel")
Species.create(name: "Convict blenny")
Species.create(name: "Convict cichlid")
Species.create(name: "Cookie-cutter shark")
Species.create(name: "Coolie loach")
Species.create(name: "Cornish Spaktailed Bream")
Species.create(name: "Cornetfish")
Species.create(name: "Cowfish")
Species.create(name: "Cownose ray")
Species.create(name: "Cow shark")
Species.create(name: "Crappie")
Species.create(name: "Creek chub")
Species.create(name: "Crestfish")
Species.create(name: "Crevice kelpfish")
Species.create(name: "Croaker")
Species.create(name: "Crocodile icefish")
Species.create(name: "Crocodile shark")
Species.create(name: "Crucian carp")
Species.create(name: "Cuchia")
Species.create(name: "Cuckoo wrasse")
Species.create(name: "Cusk-eel")
Species.create(name: "Cuskfish")
Species.create(name: "Cutlassfish")
Species.create(name: "Cutthroat eel")
Species.create(name: "Cutthroat trout")
Species.create(name: "D[edit]")
Species.create(name: "Dab")
Species.create(name: "Dace")
Species.create(name: "Daggertooth pike conger")
Species.create(name: "Damselfish")
Species.create(name: "Danio")
Species.create(name: "Darter")
Species.create(name: "Dartfish")
Species.create(name: "Dealfish")
Species.create(name: "Death Valley pupfish")
Species.create(name: "Deep sea anglerfish")
Species.create(name: "Deep sea bonefish")
Species.create(name: "Deep sea eel")
Species.create(name: "Deep sea smelt")
Species.create(name: "Deepwater cardinalfish")
Species.create(name: "Deepwater flathead")
Species.create(name: "Deepwater stingray")
Species.create(name: "Delta smelt")
Species.create(name: "Demoiselle")
Species.create(name: "Denticle herring")
Species.create(name: "Desert pupfish")
Species.create(name: "Devario")
Species.create(name: "Devil ray")
Species.create(name: "Dhufish")
Species.create(name: "Discus")
Species.create(name: "Diver: New Zealand sand diver or Long-finned sand diver")
Species.create(name: "Dogfish")
Species.create(name: "Dogfish shark")
Species.create(name: "Dogteeth tetra")
Species.create(name: "Dojo loach")
Species.create(name: "Dolly Varden trout")
Species.create(name: "Dorab")
Species.create(name: "Dorado")
Species.create(name: "Dory")
Species.create(name: "Dottyback")
Species.create(name: "Dragonet")
Species.create(name: "Dragonfish")
Species.create(name: "Dragon goby")
Species.create(name: "Driftfish")
Species.create(name: "Driftwood catfish")
Species.create(name: "Drum")
Species.create(name: "Duckbill")
Species.create(name: "Duckbilled barracudina")
Species.create(name: "Duckbill eel")
Species.create(name: "Dusky grouper")
Species.create(name: "Dwarf gourami")
Species.create(name: "Dwarf loach")
Species.create(name: "E[edit]")
Species.create(name: "Eagle ray")
Species.create(name: "Earthworm eel")
Species.create(name: "Eel")
Species.create(name: "Eelblenny")
Species.create(name: "Eel cod")
Species.create(name: "Eel-goby")
Species.create(name: "Eelpout")
Species.create(name: "Eeltail catfish")
Species.create(name: "Elasmobranch")
Species.create(name: "Electric catfish")
Species.create(name: "Electric eel")
Species.create(name: "Electric knifefish")
Species.create(name: "Electric ray")
Species.create(name: "Elephant fish")
Species.create(name: "Elephantnose fish")
Species.create(name: "Elver")
Species.create(name: "Emperor")
Species.create(name: "Emperor angelfish")
Species.create(name: "Emperor bream")
Species.create(name: "Escolar")
Species.create(name: "Eucla cod")
Species.create(name: "Eulachon")
Species.create(name: "European chub")
Species.create(name: "European eel")
Species.create(name: "European flounder")
Species.create(name: "European minnow")
Species.create(name: "European perch")
Species.create(name: "F[edit]")
Species.create(name: "False brotula")
Species.create(name: "False cat shark")
Species.create(name: "False moray")
Species.create(name: "False trevally")
Species.create(name: "Fangtooth")
Species.create(name: "Fathead sculpin")
Species.create(name: "Featherback")
Species.create(name: "Featherfin knifefish")
Species.create(name: "Fierasfer")
Species.create(name: "Fire Goby")
Species.create(name: "Filefish")
Species.create(name: "Finback cat shark")
Species.create(name: "Fingerfish")
Species.create(name: "Fire bar danio")
Species.create(name: "Firefish")
Species.create(name: "Flabby whale fish")
Species.create(name: "Flagblenny")
Species.create(name: "Flagfin")
Species.create(name: "Flagfish")
Species.create(name: "Flagtail")
Species.create(name: "Flashlight fish")
Species.create(name: "Flatfish")
Species.create(name: "Flathead")
Species.create(name: "Flathead catfish")
Species.create(name: "Flat loach")
Species.create(name: "Flier")
Species.create(name: "Flounder")
Species.create(name: "Flying characin")
Species.create(name: "Flying gurnard")
Species.create(name: "Flying fish")
Species.create(name: "Footballfish")
Species.create(name: "Forehead brooder")
Species.create(name: "Four-eyed fish")
Species.create(name: "French angelfish")
Species.create(name: "Freshwater eel")
Species.create(name: "Freshwater flyingfish")
Species.create(name: "Freshwater hatchetfish")
Species.create(name: "Freshwater herring")
Species.create(name: "Freshwater shark")
Species.create(name: "Frigate mackerel")
Species.create(name: "Frilled shark")
Species.create(name: "Frogfish")
Species.create(name: "Frogmouth catfish")
Species.create(name: "Fusilier fish")
Species.create(name: "G[edit]")
Species.create(name: "Galjoen fish")
Species.create(name: "Ganges shark")
Species.create(name: "Gar")
Species.create(name: "Garden eel")
Species.create(name: "Garibaldi")
Species.create(name: "Garpike")
Species.create(name: "Ghost carp")
Species.create(name: "Ghost fish")
Species.create(name: "Ghost flathead")
Species.create(name: "Ghost knifefish")
Species.create(name: "Ghost pipefish")
Species.create(name: "Ghost Shark")
Species.create(name: "Ghoul")
Species.create(name: "Giant danio")
Species.create(name: "Giant gourami")
Species.create(name: "Giant sea bass")
Species.create(name: "Giant wels")
Species.create(name: "Gianttail")
Species.create(name: "Gibberfish")
Species.create(name: "Gila trout")
Species.create(name: "Gizzard shad")
Species.create(name: "Glass catfish")
Species.create(name: "Glassfish")
Species.create(name: "Glass knifefish")
Species.create(name: "Glowlight danio")
Species.create(name: "Goatfish")
Species.create(name: "Goblin shark")
Species.create(name: "Goby")
Species.create(name: "Golden dojo")
Species.create(name: "Golden loach")
Species.create(name: "Golden shiner")
Species.create(name: "Golden trout")
Species.create(name: "Goldeye")
Species.create(name: "Goldfish")
Species.create(name: "Goldspotted killifish")
Species.create(name: "Gombessa")
Species.create(name: "Goosefish")
Species.create(name: "Gopher rockfish")
Species.create(name: "Gourami")
Species.create(name: "Grass carp")
Species.create(name: "Graveldiver")
Species.create(name: "Gray eel-catfish")
Species.create(name: "Grayling")
Species.create(name: "Gray mullet")
Species.create(name: "Gray reef shark")
Species.create(name: "Great white shark")
Species.create(name: "Green swordtail")
Species.create(name: "Greeneye")
Species.create(name: "Greenling")
Species.create(name: "Grenadier")
Species.create(name: "Grideye")
Species.create(name: "Ground shark")
Species.create(name: "Grouper")
Species.create(name: "Grunion")
Species.create(name: "Grunt")
Species.create(name: "Grunter")
Species.create(name: "Grunt sculpin")
Species.create(name: "Gudgeon")
Species.create(name: "Guitarfish")
Species.create(name: "Gulf menhaden")
Species.create(name: "Gulper eel")
Species.create(name: "Gulper")
Species.create(name: "Gunnel")
Species.create(name: "Guppy")
Species.create(name: "Gurnard")
Species.create(name: "H[edit]")
Species.create(name: "Haddock")
Species.create(name: "Hagfish")
Species.create(name: "Hairtail")
Species.create(name: "Hake")
Species.create(name: "Half-gill")
Species.create(name: "Halfbeak")
Species.create(name: "Halfmoon")
Species.create(name: "Halibut")
Species.create(name: "Halosaur")
Species.create(name: "Hamlet")
Species.create(name: "Hammerhead shark")
Species.create(name: "Hammerjaw")
Species.create(name: "Handfish")
Species.create(name: "Hardhead catfish")
Species.create(name: "Harelip sucker")
Species.create(name: "Hatchetfish")
Species.create(name: "Hawkfish")
Species.create(name: "Herring")
Species.create(name: "Herring smelt")
Species.create(name: "Hillstream loach")
Species.create(name: "Hog sucker")
Species.create(name: "Hoki")
Species.create(name: "Horn shark")
Species.create(name: "Horsefish")
Species.create(name: "Houndshark")
Species.create(name: "Huchen")
Species.create(name: "Humuhumu-nukunuku-apua‘a")
Species.create(name: "Hussar")
Species.create(name: "I[edit]")
Species.create(name: "Icefish")
Species.create(name: "Ide")
Species.create(name: "Ilisha")
Species.create(name: "Inanga")
Species.create(name: "Inconnu")
Species.create(name: "J[edit]")
Species.create(name: "Jack")
Species.create(name: "Jackfish")
Species.create(name: "Jack Dempsey")
Species.create(name: "Japanese eel")
Species.create(name: "Javelin")
Species.create(name: "Jawfish")
Species.create(name: "Jellynose fish")
Species.create(name: "Jewelfish")
Species.create(name: "Jewel tetra")
Species.create(name: "Jewfish")
Species.create(name: "John Dory")
Species.create(name: "jella")
Species.create(name: "K[edit]")
Species.create(name: "Kafue pike")
Species.create(name: "Kahawai")
Species.create(name: "Kaluga")
Species.create(name: "Kanyu")
Species.create(name: "Kelp perch")
Species.create(name: "Kelpfish")
Species.create(name: "Killifish")
Species.create(name: "King of herring")
Species.create(name: "Kingfish")
Species.create(name: "King-of-the-salmon")
Species.create(name: "Kissing gourami")
Species.create(name: "Knifefish")
Species.create(name: "Knifejaw")
Species.create(name: "Koi")
Species.create(name: "Kokanee")
Species.create(name: "Kokopu")
Species.create(name: "Kuhli loach")
Species.create(name: "L[edit]")
Species.create(name: "Labyrinth fish")
Species.create(name: "Ladyfish")
Species.create(name: "Lagena")
Species.create(name: "Lake chub")
Species.create(name: "Lake trout")
Species.create(name: "Lake whitefish")
Species.create(name: "Lampfish")
Species.create(name: "Lamprey")
Species.create(name: "Lancetfish")
Species.create(name: "Lanternfish")
Species.create(name: "Large-eye bream")
Species.create(name: "Largemouth bass")
Species.create(name: "Largenose fish")
Species.create(name: "Leaffish")
Species.create(name: "Leatherjacket")
Species.create(name: "Lefteye flounder")
Species.create(name: "Lemon shark")
Species.create(name: "Lemon sole")
Species.create(name: "Lenok")
Species.create(name: "Leopard danio")
Species.create(name: "Lightfish")
Species.create(name: "Lighthousefish")
Species.create(name: "Limia")
Species.create(name: "Lined sole")
Species.create(name: "Ling")
Species.create(name: "Ling cod")
Species.create(name: "Lionfish")
Species.create(name: "Livebearer")
Species.create(name: "Lizardfish")
Species.create(name: "Loach")
Species.create(name: "Loach catfish")
Species.create(name: "Loach goby")
Species.create(name: "Loach minnow")
Species.create(name: "Longfin")
Species.create(name: "Longfin dragonfish")
Species.create(name: "Longfin escolar")
Species.create(name: "Longfin smelt")
Species.create(name: "Long-finned char")
Species.create(name: "Long-finned pike")
Species.create(name: "Longjaw mudsucker")
Species.create(name: "Longneck eel")
Species.create(name: "Longnose chimaera")
Species.create(name: "Longnose dace")
Species.create(name: "Longnose lancetfish")
Species.create(name: "Longnose sucker")
Species.create(name: "Longnose whiptail catfish")
Species.create(name: "Long-whiskered catfish")
Species.create(name: "Lookdown catfish")
Species.create(name: "Loosejaw")
Species.create(name: "Lost River sucker")
Species.create(name: "Louvar")
Species.create(name: "Loweye catfish")
Species.create(name: "Luderick")
Species.create(name: "Luminous hake")
Species.create(name: "Lumpsucker")
Species.create(name: "Lungfish")
Species.create(name: "Lyretail")
Species.create(name: "M[edit]")
Species.create(name: "Mackerel")
Species.create(name: "Mackerel shark")
Species.create(name: "Madtom")
Species.create(name: "Mahi-mahi")
Species.create(name: "Mahseer")
Species.create(name: "Mail-cheeked fish")
Species.create(name: "Mako shark")
Species.create(name: "Mandarin fish")
Species.create(name: "Manefish")
Species.create(name: "Man-of-war fish")
Species.create(name: "Manta Ray")
Species.create(name: "Marblefish")
Species.create(name: "Marine hatchetfish")
Species.create(name: "Marlin")
Species.create(name: "Masu salmon")
Species.create(name: "Medaka")
Species.create(name: "Medusafish")
Species.create(name: "Megamouth shark")
Species.create(name: "Menhaden")
Species.create(name: "Merluccid hake")
Species.create(name: "Mexican blind cavefish")
Species.create(name: "Mexican golden trout")
Species.create(name: "Midshipman")
Species.create(name: "Milkfish")
Species.create(name: "Minnow")
Species.create(name: "Modoc sucker")
Species.create(name: "Mojarra")
Species.create(name: "Mola")
Species.create(name: "Molly")
Species.create(name: "Molly Miller")
Species.create(name: "Monkeyface prickleback")
Species.create(name: "Monkfish")
Species.create(name: "Mooneye")
Species.create(name: "Moonfish")
Species.create(name: "Moorish idol")
Species.create(name: "Mora")
Species.create(name: "Moray eel")
Species.create(name: "Morid cod")
Species.create(name: "Morwong")
Species.create(name: "Moses sole")
Species.create(name: "Mosquitofish")
Species.create(name: "Mosshead warbonnet")
Species.create(name: "Mouthbrooder")
Species.create(name: "Mozambique tilapia")
Species.create(name: "Mrigal")
Species.create(name: "Mud catfish (Mud cat)")
Species.create(name: "Mudfish")
Species.create(name: "Mudminnow")
Species.create(name: "Mud minnow")
Species.create(name: "Mudskipper")
Species.create(name: "Mudsucker")
Species.create(name: "Mullet")
Species.create(name: "Mummichog")
Species.create(name: "Murray cod")
Species.create(name: "Muskellunge")
Species.create(name: "Mustache triggerfish")
Species.create(name: "Mustard eel")
Species.create(name: "N[edit]")
Species.create(name: "Naked-back knifefish")
Species.create(name: "Nase")
Species.create(name: "Needlefish")
Species.create(name: "Neon tetra")
Species.create(name: "New World rivuline")
Species.create(name: "New Zealand smelt")
Species.create(name: "Nibble Fish")
Species.create(name: "Noodlefish")
Species.create(name: "North American darter")
Species.create(name: "North American freshwater catfish")
Species.create(name: "North Pacific daggertooth")
Species.create(name: "Northern anchovy")
Species.create(name: "Northern clingfish")
Species.create(name: "Northern lampfish")
Species.create(name: "Northern pearleye")
Species.create(name: "Northern pike")
Species.create(name: "Northern sea robin")
Species.create(name: "Northern squawfish")
Species.create(name: "Northern Stargazer")
Species.create(name: "Norwegian Atlantic salmon")
Species.create(name: "Nurseryfish")
Species.create(name: "Nurse shark")
Species.create(name: "O[edit]")
Species.create(name: "Oarfish")
Species.create(name: "Ocean perch")
Species.create(name: "Ocean sunfish")
Species.create(name: "Oceanic flyingfish")
Species.create(name: "Oceanic whitetip shark")
Species.create(name: "Oilfish")
Species.create(name: "Oldwife")
Species.create(name: "Old World knifefish")
Species.create(name: "Old World rivuline")
Species.create(name: "Olive flounder")
Species.create(name: "Opah")
Species.create(name: "Opaleye")
Species.create(name: "Orange roughy")
Species.create(name: "Orangespine unicorn fish")
Species.create(name: "Orangestriped triggerfish")
Species.create(name: "Orbicular batfish")
Species.create(name: "Orbicular velvetfish")
Species.create(name: "Oregon chub")
Species.create(name: "Oriental loach")
Species.create(name: "Owens pupfish")
Species.create(name: "P[edit]")
Species.create(name: "Pacific albacore")
Species.create(name: "Pacific argentine")
Species.create(name: "Pacific cod")
Species.create(name: "Pacific hake")
Species.create(name: "Pacific herring")
Species.create(name: "Pacific lamprey")
Species.create(name: "Pacific salmon")
Species.create(name: "Pacific saury")
Species.create(name: "Pacific trout")
Species.create(name: "Pacific viperfish")
Species.create(name: "Paddlefish")
Species.create(name: "Panga")
Species.create(name: "Paperbone")
Species.create(name: "Paradise fish")
Species.create(name: "Parasitic catfish")
Species.create(name: "Parrotfish")
Species.create(name: "Peacock flounder")
Species.create(name: "Peamouth")
Species.create(name: "Pearleye")
Species.create(name: "Pearlfish")
Species.create(name: "Pearl danio")
Species.create(name: "Pearl perch")
Species.create(name: "Pejerrey")
Species.create(name: "Peladillo")
Species.create(name: "Pelagic cod")
Species.create(name: "Pelican eel")
Species.create(name: "Pelican gulper")
Species.create(name: "Pencil catfish")
Species.create(name: "Pencilfish")
Species.create(name: "Pencilsmelt")
Species.create(name: "Perch")
Species.create(name: "Peter's elephantnose fish")
Species.create(name: "Pickerel")
Species.create(name: "Pigfish")
Species.create(name: "Pike characid")
Species.create(name: "Pike conger")
Species.create(name: "Pike eel")
Species.create(name: "Pike")
Species.create(name: "Pikeblenny")
Species.create(name: "Pikehead")
Species.create(name: "Pikeperch")
Species.create(name: "Pilchard")
Species.create(name: "Pilot fish")
Species.create(name: "Pineapplefish")
Species.create(name: "Pineconefish")
Species.create(name: "Pink salmon")
Species.create(name: "Píntano")
Species.create(name: "Pipefish")
Species.create(name: "Piranha")
Species.create(name: "Pirarucu")
Species.create(name: "Pirate perch")
Species.create(name: "Plaice")
Species.create(name: "Platy")
Species.create(name: "Platyfish")
Species.create(name: "Pleco")
Species.create(name: "Plownose chimaera")
Species.create(name: "Plunderfish")
Species.create(name: "Poacher")
Species.create(name: "Pollyfish")
Species.create(name: "Pollock")
Species.create(name: "Pomfret")
Species.create(name: "Pompano")
Species.create(name: "Pompano dolphinfish")
Species.create(name: "Ponyfish")
Species.create(name: "Poolfish")
Species.create(name: "Popeye catafula")
Species.create(name: "Porbeagle shark")
Species.create(name: "Porcupinefish")
Species.create(name: "Porgy")
Species.create(name: "Port Jackson shark")
Species.create(name: "Powen")
Species.create(name: "Priapumfish")
Species.create(name: "Prickleback")
Species.create(name: "Pricklefish")
Species.create(name: "Prickly shark")
Species.create(name: "Pristella maxillaris")
Species.create(name: "Prowfish")
Species.create(name: "Pufferfish")
Species.create(name: "Pumpkinseed")
Species.create(name: "Pupfish")
Species.create(name: "Pygmy sunfish")
Species.create(name: "Q[edit]")
Species.create(name: "Queen danio")
Species.create(name: "Queen parrotfish")
Species.create(name: "Queen triggerfish")
Species.create(name: "Quillback")
Species.create(name: "Quillfish")
Species.create(name: "R[edit]")
Species.create(name: "Rabbitfish")
Species.create(name: "Raccoon butterfly fish")
Species.create(name: "Ragfish")
Species.create(name: "Rainbow trout")
Species.create(name: "Rainbowfish")
Species.create(name: "Rasbora")
Species.create(name: "Ratfish")
Species.create(name: "Rattail")
Species.create(name: "Ray")
Species.create(name: "Razorback sucker")
Species.create(name: "Razorfish")
Species.create(name: "Red salmon")
Species.create(name: "Red snapper")
Species.create(name: "Redfin perch")
Species.create(name: "Redfish")
Species.create(name: "Redhorse sucker")
Species.create(name: "Redlip blenny")
Species.create(name: "Redmouth whalefish")
Species.create(name: "Redside")
Species.create(name: "Redtooth triggerfish")
Species.create(name: "Red velvetfish")
Species.create(name: "Red whalefish")
Species.create(name: "Reedfish")
Species.create(name: "Reef triggerfish")
Species.create(name: "Regal whiptail catfish")
Species.create(name: "Remora")
Species.create(name: "Requiem shark")
Species.create(name: "Ribbon eel")
Species.create(name: "Ribbon sawtail fish")
Species.create(name: "Ribbonbearer")
Species.create(name: "Ribbonfish")
Species.create(name: "Rice eel")
Species.create(name: "Ricefish")
Species.create(name: "Ridgehead")
Species.create(name: "Riffle dace")
Species.create(name: "Righteye flounder")
Species.create(name: "Rio Grande perch")
Species.create(name: "River loach")
Species.create(name: "River shark")
Species.create(name: "River stingray")
Species.create(name: "Rivuline")
Species.create(name: "Roach")
Species.create(name: "Roanoke bass")
Species.create(name: "Rock bass")
Species.create(name: "Rock beauty")
Species.create(name: "Rock cod")
Species.create(name: "Rocket danio")
Species.create(name: "Rockfish")
Species.create(name: "Rockling")
Species.create(name: "Rockweed gunnel")
Species.create(name: "Rohu")
Species.create(name: "Ronquil")
Species.create(name: "Roosterfish")
Species.create(name: "Ropefish")
Species.create(name: "Rough pomfret")
Species.create(name: "Rough scad")
Species.create(name: "Rough sculpin")
Species.create(name: "Roughy")
Species.create(name: "Roundhead")
Species.create(name: "Round herring")
Species.create(name: "Round stingray")
Species.create(name: "Round whitefish")
Species.create(name: "Rudd")
Species.create(name: "Rudderfish")
Species.create(name: "Ruffe")
Species.create(name: "Russian sturgeon")
Species.create(name: "S[edit]")
Species.create(name: "Sábalo")
Species.create(name: "Sabertooth")
Species.create(name: "Saber-toothed blenny")
Species.create(name: "Sabertooth fish")
Species.create(name: "Sablefish")
Species.create(name: "Sacramento blackfish")
Species.create(name: "Sacramento splittail")
Species.create(name: "Sailback scorpionfish")
Species.create(name: "Sailbearer")
Species.create(name: "Sailfin silverside")
Species.create(name: "Sailfish")
Species.create(name: "Salamanderfish")
Species.create(name: "Salmon")
Species.create(name: "Salmon shark")
Species.create(name: "Sandbar shark")
Species.create(name: "Sandburrower")
Species.create(name: "Sand dab")
Species.create(name: "Sand diver")
Species.create(name: "Sand eel")
Species.create(name: "Sandfish")
Species.create(name: "Sand goby")
Species.create(name: "Sand knifefish")
Species.create(name: "Sand lance")
Species.create(name: "Sandperch")
Species.create(name: "Sandroller")
Species.create(name: "Sand stargazer")
Species.create(name: "Sand tiger")
Species.create(name: "Sand tilefish")
Species.create(name: "Sarcastic fringehead")
Species.create(name: "Sardine")
Species.create(name: "Sargassum fish")
Species.create(name: "Sauger")
Species.create(name: "Saury")
Species.create(name: "Sawfish")
Species.create(name: "Saw shark")
Species.create(name: "Sawtooth eel")
Species.create(name: "Scabbard fish")
Species.create(name: "Scaleless black dragonfish")
Species.create(name: "Scaly dragonfish")
Species.create(name: "Scat")
Species.create(name: "Scissor-tail rasbora")
Species.create(name: "Scorpionfish")
Species.create(name: "Sculpin")
Species.create(name: "Scup")
Species.create(name: "Scythe butterfish")
Species.create(name: "Sea bass")
Species.create(name: "Sea bream")
Species.create(name: "Sea catfish")
Species.create(name: "Sea chub")
Species.create(name: "Sea devil")
Species.create(name: "Sea dragon")
Species.create(name: "Sea lamprey")
Species.create(name: "Sea raven")
Species.create(name: "Sea snail")
Species.create(name: "Sea toad")
Species.create(name: "Seahorse")
Species.create(name: "Seamoth")
Species.create(name: "Searobin")
Species.create(name: "Sevan trout")
Species.create(name: "Seatrout")
Species.create(name: "Sergeant major")
Species.create(name: "Shad")
Species.create(name: "Shark")
Species.create(name: "Sharksucker")
Species.create(name: "(Caribbean) Sharp-Nose Puffer")
Species.create(name: "Sheatfish")
Species.create(name: "Shingle Fish")
Species.create(name: "Sheepshead")
Species.create(name: "Sheepshead minnow")
Species.create(name: "Shell-ear")
Species.create(name: "Shiner")
Species.create(name: "Shortnose chimaera")
Species.create(name: "Shortnose greeneye")
Species.create(name: "Shortnose sucker")
Species.create(name: "Shovelnose sturgeon")
Species.create(name: "Shrimpfish")
Species.create(name: "Siamese fighting fish")
Species.create(name: "Sillago")
Species.create(name: "Silver carp")
Species.create(name: "Silver dollar")
Species.create(name: "Silver driftfish")
Species.create(name: "Silver hake")
Species.create(name: "Silverside")
Species.create(name: "Sind danio")
Species.create(name: "Sixgill ray")
Species.create(name: "Sixgill shark")
Species.create(name: "Skate")
Species.create(name: "Skilfish")
Species.create(name: "Skipjack tuna")
Species.create(name: "Skipping goby")
Species.create(name: "Slender barracudina")
Species.create(name: "Slender mola")
Species.create(name: "Slender snipe eel")
Species.create(name: "Sleeper")
Species.create(name: "Sleeper shark")
Species.create(name: "Slickhead")
Species.create(name: "Slimehead")
Species.create(name: "Slimy mackerel")
Species.create(name: "Slimy sculpin")
Species.create(name: "Slipmouth")
Species.create(name: "Smalleye squaretail")
Species.create(name: "Smalltooth sawfish")
Species.create(name: "Smelt")
Species.create(name: "Smelt-whiting")
Species.create(name: "Smooth dogfish")
Species.create(name: "Smoothtongue")
Species.create(name: "Snailfish")
Species.create(name: "Snake eel")
Species.create(name: "Snakehead")
Species.create(name: "Snake mackerel")
Species.create(name: "Snake mudhead")
Species.create(name: "Snapper")
Species.create(name: "Snipe eel")
Species.create(name: "Snipefish")
Species.create(name: "Snoek")
Species.create(name: "Snook")
Species.create(name: "Snubnose eel")
Species.create(name: "Snubnose parasitic eel")
Species.create(name: "Soapfish")
Species.create(name: "Sockeye salmon")
Species.create(name: "Soldierfish")
Species.create(name: "Sole")
Species.create(name: "South American darter")
Species.create(name: "South American Lungfish")
Species.create(name: "Southern Dolly Varden")
Species.create(name: "Southern flounder")
Species.create(name: "Southern grayling")
Species.create(name: "Southern hake")
Species.create(name: "Southern sandfish")
Species.create(name: "Southern smelt")
Species.create(name: "Spadefish")
Species.create(name: "Spaghetti eel")
Species.create(name: "Spanish mackerel")
Species.create(name: "Spearfish")
Species.create(name: "Speckled trout")
Species.create(name: "Spiderfish")
Species.create(name: "Spikefish")
Species.create(name: "Spinefoot")
Species.create(name: "Spiny-back")
Species.create(name: "Spiny basslet")
Species.create(name: "Spiny dogfish")
Species.create(name: "Spiny dwarf catfish")
Species.create(name: "Spiny eel")
Species.create(name: "Spinyfin")
Species.create(name: "Splitfin")
Species.create(name: "Spookfish")
Species.create(name: "Spotted danio")
Species.create(name: "Spotted dogfish")
Species.create(name: "Sprat")
Species.create(name: "Springfish")
Species.create(name: "Squarehead catfish")
Species.create(name: "Squaretail")
Species.create(name: "Squawfish")
Species.create(name: "Squeaker")
Species.create(name: "Squirrelfish")
Species.create(name: "Staghorn sculpin")
Species.create(name: "Stargazer")
Species.create(name: "Starry flounder")
Species.create(name: "Steelhead")
Species.create(name: "Stickleback")
Species.create(name: "Stingfish")
Species.create(name: "Stingray")
Species.create(name: "Stonecat")
Species.create(name: "Stonefish")
Species.create(name: "Stoneroller minnow")
Species.create(name: "Straptail")
Species.create(name: "Stream catfish")
Species.create(name: "Streamer fish")
Species.create(name: "Striped bass")
Species.create(name: "Striped burrfish")
Species.create(name: "Sturgeon")
Species.create(name: "Sucker")
Species.create(name: "Suckermouth armored catfish")
Species.create(name: "Summer flounder")
Species.create(name: "Sundaland noodlefish")
Species.create(name: "Sunfish (opah)")
Species.create(name: "Sunfish (mola mola)")
Species.create(name: "Surf sardine")
Species.create(name: "Surfperch")
Species.create(name: "Surgeonfish")
Species.create(name: "Swallower")
Species.create(name: "Swamp-eel")
Species.create(name: "Swampfish")
Species.create(name: "Sweeper")
Species.create(name: "Swordfish")
Species.create(name: "Swordtail")
Species.create(name: "T[edit]")
Species.create(name: "Tadpole cod")
Species.create(name: "Tadpole fish")
Species.create(name: "Tailor")
Species.create(name: "Taimen")
Species.create(name: "Tang")
Species.create(name: "Tapetail")
Species.create(name: "Tarpon")
Species.create(name: "Tarwhine")
Species.create(name: "Telescopefish")
Species.create(name: "Temperate bass")
Species.create(name: "Temperate ocean-bass")
Species.create(name: "Temperate perch")
Species.create(name: "Tench")
Species.create(name: "Tenpounder")
Species.create(name: "Tenuis")
Species.create(name: "Tetra")
Species.create(name: "Thorny catfish")
Species.create(name: "Thornfish")
Species.create(name: "Thornyhead")
Species.create(name: "Threadfin")
Species.create(name: "Threadfin bream")
Species.create(name: "Threadsail")
Species.create(name: "Threadtail")
Species.create(name: "Three spot gourami")
Species.create(name: "Threespine stickleback")
Species.create(name: "Three-toothed puffer")
Species.create(name: "Thresher shark")
Species.create(name: "Tidewater goby")
Species.create(name: "Tiger barb")
Species.create(name: "Tigerperch")
Species.create(name: "Tiger shark")
Species.create(name: "Tiger shovelnose catfish")
Species.create(name: "Tilapia")
Species.create(name: "Tilefish")
Species.create(name: "Titan triggerfish")
Species.create(name: "Toadfish")
Species.create(name: "Tommy ruff")
Species.create(name: "Tompot blenny")
Species.create(name: "Tonguefish")
Species.create(name: "Tope")
Species.create(name: "Topminnow")
Species.create(name: "Torpedo")
Species.create(name: "Torrent catfish")
Species.create(name: "Torrent fish")
Species.create(name: "Trahira")
Species.create(name: "Treefish")
Species.create(name: "Trevally")
Species.create(name: "Triggerfish")
Species.create(name: "Triplefin blenny")
Species.create(name: "Triplespine")
Species.create(name: "Tripletail")
Species.create(name: "Tripod fish")
Species.create(name: "Trout")
Species.create(name: "Trout cod")
Species.create(name: "Trout-perch")
Species.create(name: "Trumpeter")
Species.create(name: "Trumpetfish")
Species.create(name: "Trunkfish")
Species.create(name: "Tubeblenny")
Species.create(name: "Tube-eye")
Species.create(name: "Tube-snout")
Species.create(name: "Tubeshoulder")
Species.create(name: "Tui chub")
Species.create(name: "Tuna")
Species.create(name: "Turbot")
Species.create(name: "Turkeyfish")
Species.create(name: "U[edit]")
Species.create(name: "Uaru")
Species.create(name: "Unicorn fish")
Species.create(name: "Upside-down catfish")
Species.create(name: "V[edit]")
Species.create(name: "Velvet belly lanternshark")
Species.create(name: "Velvet catfish")
Species.create(name: "Velvetfish")
Species.create(name: "Vendace")
Species.create(name: "Vimba")
Species.create(name: "Viperfish")
Species.create(name: "W[edit]")
Species.create(name: "Wahoo")
Species.create(name: "Walking catfish")
Species.create(name: "Wallago")
Species.create(name: "Walleye")
Species.create(name: "Walleye pollock")
Species.create(name: "Walu")
Species.create(name: "Warbonnet")
Species.create(name: "Warmouth")
Species.create(name: "Warty angler")
Species.create(name: "Waryfish")
Species.create(name: "Wasp fish")
Species.create(name: "Weasel shark")
Species.create(name: "Weatherfish")
Species.create(name: "Weever")
Species.create(name: "Weeverfish")
Species.create(name: "Wels catfish")
Species.create(name: "Whale catfish")
Species.create(name: "Whalefish")
Species.create(name: "Whale shark")
Species.create(name: "Whiff")
Species.create(name: "Whiptail gulper")
Species.create(name: "Whitebait")
Species.create(name: "White croaker")
Species.create(name: "Whitefish")
Species.create(name: "White marlin")
Species.create(name: "White shark")
Species.create(name: "Whitetip reef shark")
Species.create(name: "Whiting")
Species.create(name: "Wobbegong")
Species.create(name: "Wolf-eel")
Species.create(name: "Wolffish")
Species.create(name: "Wolf-herring")
Species.create(name: "Woody sculpin")
Species.create(name: "Worm eel")
Species.create(name: "Wormfish")
Species.create(name: "Wrasse")
Species.create(name: "Wrymouth")
Species.create(name: "Y[edit]")
Species.create(name: "Yellow-and-black triplefin")
Species.create(name: "Yellowbanded perch")
Species.create(name: "Yellow bass")
Species.create(name: "Yellow-edged moray")
Species.create(name: "Yellow-eye mullet")
Species.create(name: "Yellowhead jawfish")
Species.create(name: "Yellowfin croaker")
Species.create(name: "Yellowfin cutthroat trout")
Species.create(name: "Yellowfin grouper")
Species.create(name: "Yellowfin pike")
Species.create(name: "Yellowfin surgeonfish")
Species.create(name: "Yellowfin tuna")
Species.create(name: "Yellow jack")
Species.create(name: "Yellowmargin triggerfish")
Species.create(name: "Yellow moray")
Species.create(name: "Yellow perch")
Species.create(name: "Yellowtail")
Species.create(name: "Yellowtail amberjack")
Species.create(name: "Yellowtail barracuda")
Species.create(name: "Yellowtail clownfish")
Species.create(name: "Yellowtail horse mackerel")
Species.create(name: "Yellowtail kingfish")
Species.create(name: "Yellowtail snapper")
Species.create(name: "Yellow tang")
Species.create(name: "Yellow weaver")
Species.create(name: "Yellowbelly tail catfish")
Species.create(name: "Z[edit]")
Species.create(name: "Zander")
Species.create(name: "Zebra bullhead shark")
Species.create(name: "Zebra danio")
Species.create(name: "Zebrafish")
Species.create(name: "Zebra lionfish")
Species.create(name: "Zebra loach")
Species.create(name: "Zebra oto")
Species.create(name: "Zebra pleco")
Species.create(name: "Zebra shark")
Species.create(name: "Zebra tilapia")
Species.create(name: "Ziege")
Species.create(name: "Zingel")
Species.create(name: "Zebra trout")
Species.create(name: "Zebra turkeyfish")